### ISSUE TITLE
im not able to "import glassnode"

### ISSUE THREAD

**Issue by ECBSJ** [SerendipityIsMe/glassnode#1]
in the test file i get an error for "import glassnode"

am i supposed to install this as a library first? what things do i need to change on the glassnode.py file besides inserting my own API key?

basically i just copied and pasted your glassnode.py file and replaced it with my own API key. Then i made a new file trying to run the test.py file with my own API key....

any help is appreciated

**Comment by SerendipityIsMe** [comment]
You need to make sure python can access glassnode.py, ie it needs to be in the Python Path. I suggest you create a folder, put test.py and glassnode.py inside the folder, and run test.py. Since they're in the same folder and glassnode.py is thus in the path python searches, it should run fine. Let me know if it works out!

**Comment by ECBSJ** [comment]
got it. thanks! ill play around with it from here!

**Comment by ECBSJ** [comment]
how come on the test.py file theres not option to change the asset name. I can only specify what asset on the glassnode.py file?

**Comment by SerendipityIsMe** [comment]
There is the option. You just need to put **asset = 'ETH'** as one of the function arguments in test.py, for example. If you don't specify any asset, it defaults to BTC. (Also, make sure the metric you specify exists for the asset you choose!)

**Comment by ECBSJ** [comment]
ahhh just made a noob play by not adding the comma after it. thanks!

**Comment by ECBSJ** [comment]
it seems like you didnt add a parameter for the frequency interval (i.e., 1h, 10m or 24h (default))....how would i do this?

**Comment by SerendipityIsMe** [comment]
I did it just now, at your request. It is controlled by the new parameter called 'resolution'. See the updated source code and docstring for an explanation.

**Comment by ECBSJ** [comment]
Thank you!

**Comment by ECBSJ** [comment]
Hello, anyway I could add in multiple tickers in one request rather than having to duplicate the request. For example if I want to get the price results for AMPL, ETH, and YFI, I want to just place the tickers in one line:

`AMP_PRICE_RESULTS = gn.glassnode(
    '/v1/metrics/market/price_usd_ohlc', 
    start = [2020, 6, 26], 
    until = [2020, 9, 20],
    api_key = 'xxx', 
    asset = 'AMPL','ETH','YFI',
    status = False, 
    headers = False,
    resolution = '24h',
    wait = 30
    )`

rather than duplicating it like this:

`ETH_PRICE_RESULTS = gn.glassnode(
    '/v1/metrics/market/price_usd_ohlc', 
    start = [2020, 6, 1], 
    until = [2020, 9, 20],
    api_key = 'xxx', 
    asset = 'ETH',
    status = False, 
    headers = False,
    resolution = '24h',
    wait = 30
    )

AMPL_PRICE_RESULTS = gn.glassnode(
    '/v1/metrics/market/price_usd_ohlc', 
    start = [2020, 6, 1], 
    until = [2020, 9, 20],
    api_key = 'xxx', 
    asset = 'AMPL',
    status = False, 
    headers = False,
    resolution = '24h',
    wait = 30
    )

YFI_PRICE_RESULTS = gn.glassnode(
    '/v1/metrics/market/price_usd_ohlc', 
    start = [2020, 6, 1], 
    until = [2020, 9, 20],
    api_key = 'xxx', 
    asset = 'YFI',
    status = False, 
    headers = False,
    resolution = '24h',
    wait = 30
    )`

**Comment by SerendipityIsMe** [comment]
Doing so is outside of the scope of this repository, which is just a simple interface for interacting with the API. Nonethless, you can easily accomplish this yourself by defining a python function:

```
import glassnode as gn
import pandas as pd

def multiasset_price(assets):
        dflist = [None] * len(assets)
        for index, asset in enumerate(assets):
                dflist[index] = gn.glassnode(
                '/v1/metrics/market/price_usd_ohlc', 
                start = [2015, 1, 13], 
                until = [2020, 1, 15],
                asset = f'{assets[index]}',
                status = True, 
                headers = False,
                wait = 10
                )
        return dflist

assets = ['ETH', 'YFI', 'AMPL']
price_list = multiasset_price(assets)
print(price_list)
```

**Comment by ECBSJ** [comment]
thank you very much!
